- name: restart-nginx
  ansible.builtin.sysvinit:
    name: nginx
    state: restarted
  notify: copy_templete

- name: copy_templete
  ansible.builtin.template:
    src: index.html
    dest: /usr/share/nginx/html
    mode: 0644
  notify: copy_style

- name: copy_style
  ansible.builtin.copy:
    src: style.css
    dest: /usr/share/nginx/html
    mode: 0644 
